import { Participant } from './types';

export const MOCK_PARTICIPANTS: Participant[] = [
  {
    id: '1',
    name: 'Thang Tran',
    avatar: 'https://i.pravatar.cc/200?img=1',
    isMuted: true,
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Finish home work',
    progress: 35,
  },
  {
    id: '2',
    name: 'Minh Nguyen',
    avatar: 'https://i.pravatar.cc/200?img=2',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Read documentation',
    progress: 60,
  },
  {
    id: '3',
    name: 'Linh Pham',
    avatar: 'https://i.pravatar.cc/200?img=3',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'UI polishing',
    progress: 80,
  },
  {
    id: '4',
    name: 'Huy Le',
    avatar: 'https://i.pravatar.cc/200?img=4',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Fix bugs',
    progress: 45,
  },
  {
    id: '5',
    name: 'An Vo',
    avatar: 'https://i.pravatar.cc/200?img=5',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Write tests',
    progress: 25,
  },
  {
    id: '6',
    name: 'Khoa Dang',
    avatar: 'https://i.pravatar.cc/200?img=6',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Refactor components',
    progress: 70,
  },
  {
    id: '7',
    name: 'Trang Bui',
    avatar: 'https://i.pravatar.cc/200?img=7',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Design review',
    progress: 90,
  },
  {
    id: '8',
    name: 'Phuc Hoang',
    avatar: 'https://i.pravatar.cc/200?img=8',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'API integration',
    progress: 55,
  },
  {
    id: '9',
    name: 'Vy Truong',
    avatar: 'https://i.pravatar.cc/200?img=9',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Prepare slides',
    progress: 40,
  },
  {
    id: '10',
    name: 'Nam Do',
    avatar: 'https://i.pravatar.cc/200?img=10',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Debug mobile layout',
    progress: 65,
  },
  {
    id: '11',
    name: 'Alex Chen',
    avatar: 'https://i.pravatar.cc/200?img=11',
    isVideoOff: false, // đang bật video
    isActive: true,
    taskTitle: 'Live coding',
    progress: 20,
  },
  {
    id: '12',
    name: 'Sarah Kim',
    avatar: 'https://i.pravatar.cc/200?img=12',
    isVideoOff: true,
    isActive: true,
    taskTitle: 'Finish dashboard',
    progress: 100,
  },
];

export const ROOM_NAME = 'Code & Coffee';
